version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 120
      runas: root
    - location: scripts/start_server
      timeout: 120
      runas: root

